title: "ETC3550/ETC5550 Applied&nbsp;forecasting"
pdf-engine: pdflatex
fig-width: 7.5
fig-height: 3.5
include-in-header: header.tex
format:
  beamer:
    theme: monash
    aspectratio: 169
    fontsize: 14pt
    section-titles: false
    knitr:
      opts_chunk:
        dev: "cairo_pdf"
execute:
  echo: false
  message: false
  warning: false
